---
title: "Reading List for Econ 2367.02: Current Economic Issues in the U.S."
author: ""
date: "Fall 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a tentative list of readings that I will update as the course progresses. I will add articles to "old" topics (i.e. topics we have already discussed) so it will be helpful for you to refer to the list now and then, especially when you are looking for sources for your essay assignments. I have also included a section on sources of and about economics research. 

## Helpful sources

- [Journal of Economics Perspectives](https://www.aeaweb.org/journals/jep/about-jep) provides overviews of research topics and targeted at non-specialists
- The [National Bureau of Economic Research (NBER)](www.nber.org) is a great resource for the latest working papers in economics. The [NBER Digest](http://www.nber.org/digest/) provides non-technical summaries of papers. 
- [Microeconomic Insights](http://microeconomicinsights.org/) provides summaries of the latest economics research
- [IZA](iza.org) is similar to the NBER and provides working papers.

\* = assigned reading for class

## Week 1

[\*Noah Smith, How to Give a Cool Appraisal to Hot Economics Studies](https://www.bloomberg.com/view/articles/2017-03-21/how-to-give-a-cool-appraisal-to-hot-economics-studies)

[Dina Pomeranz, Impact evaluation methods in public economics](https://www.zora.uzh.ch/id/eprint/136558/1/Pomeranz_Impact-Evaluation-Methods-final.pdf)

## Week 2 (Minimum Wage)

[\*John Schmitt (skim pages 1-5; read pp. 11-13 starting from "Adjustment Channels")](http://cepr.net/documents/publications/min-wage-2013-02.pdf)

[\*Jordan Weissmann, Jobless in Seattle](http://www.slate.com/articles/business/moneybox/2014/05/seattle_might_raise_its_minimum_wage_to_15_this_is_not_a_good_idea.html)

[\*Luca and Luca, Survival of the Fittest: The Impact of the Minimum Wage on Firm Exit (sections I and II)](http://www.hbs.edu/faculty/Publication%20Files/MW_Exit_7a89f82f-b2fa-42f2-9a0e-f8a61e95b679.pdf)

[Lordan and Neumark, People Versus Machines: The Impact of Minimum Wages on Automatable Jobs](http://nber.org/papers/w23667)

[Catherine Rampell, 'Free lunches' like the $15 minimum wage may hurt the people they’re meant to help](https://www.washingtonpost.com/opinions/free-lunches-like-the-15-minimum-wage-may-hurt-the-people-theyre-meant-to-help/2017/08/07/d55e8476-7bad-11e7-9d08-b79f191668ed_story.html)

## Week 3 (Immigration)

[\*Report by the National Academy of Sciences on The Economic and Fiscal Consequences of Immigration; read the "Summary" chapter, which the hyperlink goes directly to](https://www.nap.edu/read/23550/chapter/2)

[\*Planet Money, If Economists Controlled the Borders](http://www.npr.org/blogs/money/2014/04/02/298383246/episode-436-if-economists-controlled-the-borders)

[\*The Place Premium: Wage Differences for Identical Workers across the U.S. Border; read intro and conclusion](https://www.cgdev.org/sites/default/files/16352_file_CMP_place_premium_148.pdf)

George Borjas, Immigration, [http://www.econlib.org/library/Enc/Immigration.html](http://www.econlib.org/library/Enc/Immigration.html)

## Week 4 (Economics of Cities)

[\*David Audretsch, IZA World of Labor, Knowledge Spillovers and Future Jobs](https://wol.iza.org/uploads/articles/218/pdfs/knowledge-spillovers-and-future-jobs.pdf)

[Enrico Moretti, The New Geography of Jobs (book)](https://www.amazon.com/New-Geography-Jobs-Enrico-Moretti/dp/0544028058)

[Glaeser and Gottlieb, The Wealth of Cities: Agglomeration Economies and Spatial Equilibrium in the United States (some parts are very technical which you can skip, but the non-technical parts are clearly written)](http://www.nber.org/papers/w14806.pdf)

[\*Chetty, Hendren, and Katz, Moving to Opportunity executive summary](http://www.equality-of-opportunity.org/assets/documents/mto_exec_summary.pdf)

## Week 5

\*Rochet and Tirole, Two-sided Markets: An Overview (uploaded on Carmen; read up to but not including section 3)

\*WSJ, Americans Losing Faith in College Degrees, Poll Finds (uploaded on Carmen)

## Week 6 (Economics of Science and Innovation)

[\**Undiscovered* podcast, episode is called *The Wastebook*](http://www.undiscoveredpodcast.org/the-wastebook.html)

[\*Hal Varian, Review of Mokyr's "Gifts of Athena"; also uploaded on Carmen](https://www.jstor.org/stable/3217252)

[Jon Marcus, The Decline of the Midwest's Public Universities Threatens to Wreck Its Most Vibrant Economies (article in The Atlantic)](https://www.theatlantic.com/business/archive/2017/10/midwestern-public-research-universities-funding/542889/)

[Paula Stephan, The Economics of Science](https://www.jstor.org/stable/2729500)

[Paula Stephan, How Economics Shapes Science (book)](https://www.amazon.com/Economics-Shapes-Science-Paula-Stephan/dp/0674088166)

## Week 7 (Technology and Inequality)

[\*TED Talk by David Autor](https://www.ted.com/talks/david_autor_why_are_there_still_so_many_jobs)

[David Autor, Skills, education, and the rise of earnings inequality among the "other 99 percent"](http://science.sciencemag.org/content/344/6186/843)

[Gabriel Zucman, slides from one semester course on inequality](http://gabriel-zucman.eu/econ133/)

[\**The Basic Income Experiment*, Planet Money podcast](http://www.npr.org/sections/money/2017/09/22/552850245/episode-796-the-basic-income-experiment)

[\**Why Some People Love Tax Day*, Planet Money podcast](http://www.npr.org/sections/money/2013/04/12/177063399/episode-451-why-some-people-love-tax-day)

[\*Summary of evidence on cash transfers in developing countries, GiveDirectly website](https://www.givedirectly.org/research-on-cash-transfers)

[Ioana Marinescu, No Strings Attached](http://www.marinescu.eu/Marinescu_UBI_review_2017.pdf)

[New York Times quiz](https://www.nytimes.com/interactive/2016/06/03/upshot/up-college-unemployment-quiz.html)

[Welfare State, 50 things that made the modern economy podcast by Tim Harford](http://www.bbc.co.uk/programmes/w3csv3gv)

## Week 8 (Matching)

[\*Make me a match, Freakonomics podcast](http://freakonomics.com/podcast/make-me-a-match-a-new-freakonomics-radio-episode/)

[\*Noble Matching, Marginal Revolution blogpost; read first 4 paragraphs explaining the Gale-Shapley algorithm, up to the sentence "Thus, the algorithm produces a stable match."](http://marginalrevolution.com/marginalrevolution/2012/10/noble-matching.html)

[Econtalk, Alvin Roth on Matching Markets](http://www.econtalk.org/archives/2015/07/alvin_roth_on_m.html)

## Week 9 (Gender)

[\*Sarah Kliff, The truth about the gender wage gap](https://www.vox.com/2017/9/8/16268362/gender-wage-gap-explained)

[\*Freakonomics podcast, What are Gender Barriers Made of?](http://freakonomics.com/podcast/gender-barriers/)

[Freakonomics podcast, The True Story of the Gender Wage Gap](http://freakonomics.com/podcast/the-true-story-of-the-gender-pay-gap-a-new-freakonomics-radio-podcast/)

[EVIDENCE ON SELF-STEREOTYPING AND THE
CONTRIBUTION OF IDEAS, Katherine Baldiga Coffman](https://drive.google.com/file/d/0B2fD6UtLe0bcNHlCWnJlT1lpV28/view)

[Acting Wife; Bursztyn, Fujiwara, Pallais](http://www.nber.org/papers/w23043.pdf)



## Week 10 (Health)

[*The RAND Health Insurance Experiment: A Retrospective at 40 Years (video)](https://www.rand.org/multimedia/video/2017/01/13/health-insurance-experiment-retrospective-40-years.html)

[*Oregon Health Insurance Experiment website; look at the **Background** and **Results** pages](http://www.nber.org/oregon/2.background.html)

[*Oregon HIE paper; read introduction](http://www.nber.org/papers/w17190.pdf)

Questions:
What were the RAND and Oregon experiments trying to test? What did they find? Did those findings surprise you?

## Week 11 (Crime/Addiction, Environment)

- Wednesday
    + [\*What was Gary Becker's biggest mistake?](http://marginalrevolution.com/marginalrevolution/2015/09/what-was-gary-beckers-biggest-mistake.html)
    + [\*The Economics of Addiction](http://www.slate.com/articles/arts/the_undercover_economist/2007/08/the_economics_of_addiction.html)
    + [\*An Economist Gets Stoned, Planet Money podcast](http://www.npr.org/sections/money/2010/01/podcast_an_economist_gets_ston.html)
  

- Friday
    + [\*Will Economic Growth Destroy the Planet, Planet Money podcast](http://www.npr.org/sections/money/2011/10/25/141701559/the-tuesday-podcast-will-economic-growth-destroy-the-planet)
    
Questions:

- What do you think of the idea that crime and addiction are rational? If addiction is rational, should we do away with limits on addictive substances? 

- Should we eliminate all pollution? Why or why not? 
- What value do enviromental goods have? E.g. what are some benefits of trees?

## Week 12 (Behavioral economics; replication in the sciences)

- [\*Raj Chetty, Behavioral Economics and Public Policy: A Pragmatic Perspective; read the introduction](http://www.nber.org/papers/w20928)
- [\*When the Revolution Came for Amy Cuddy](https://www.nytimes.com/2017/10/18/magazine/when-the-revolution-came-for-amy-cuddy.html)
- [Nudge, Nudge, Nobel. Planet Money podcast on Richard Thaler](http://www.npr.org/sections/money/2017/11/01/561421807/episode-803-nudge-nudge-nobel)

Questions

- How can behavioral economics inform public policy?
- Has the article on Amy Cuddy changed how you evaluate expert opinion?
